import 'package:flutter/material.dart';

Map<String, Color> avatarColors = {
  "A": Colors.red,
  "B": Colors.redAccent,
  "C": Colors.blueAccent,
  "D": Colors.brown,
  "E": Colors.blue,
  "F": Colors.grey,
  "G": Colors.green,
  "H": Colors.yellow,
  "I": Colors.yellowAccent,
  "J": Colors.purple,
  "K": Colors.deepOrange,
  "L": Colors.deepPurple,
  "M": Colors.orange,
  "N": Colors.pink,
  "O": Colors.teal,
  "P": Colors.green,
  "Q": Colors.indigo,
  "R": Colors.red,
  "S": Colors.tealAccent,
  "T": Colors.lightBlue,
  "U": Colors.indigoAccent,
  "V": Colors.pinkAccent,
  "W": Colors.orangeAccent,
  "X": Colors.deepPurpleAccent,
  "Y": Colors.lightBlue,
  "Z": Colors.lime,
};
